[package]
name = "advent2025"
version = "0.1.0"
edition = "2021"

[dependencies]
advent-grid = { git = "https://github.com/djrideout/advent-grid.git", version = "0.1.0" }
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
regex = "1.12.2"
